#!/bin/sh

set -e

#db='/home/drinkomatic/micropay.db'
db='/home/paw/tmp/micropay.db'
db='/home/paw/Dropbox/studentergaarden/netudvalg/drinkomatic/micropay.db'
#card='/dev/ttyS0'
barcode='/dev/ttyUSB0'

card='/dev/ttyUSB0'
barcode='/home/paw/tmp/testpipe'
barcode='/dev/ttyUSB1'
dir="`dirname $0`"

stty -F"$card" raw -echo -hup 9600
stty -F"$barcode" raw -echo -hup 9600

cd "$dir"
exec lem drinkomatic.lua "$db" "$card" "$barcode"
